# Generated by Django 5.2.7 on 2025-10-30 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='swipeevent',
            name='music_swipe_user_id_1c9839_idx',
        ),
        migrations.RemoveField(
            model_name='swipeevent',
            name='user_id',
        ),
        migrations.AddField(
            model_name='swipeevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipe_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
