# Generated by Django 4.2.25 on 2025-10-30 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrackLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('provider_track_id', models.CharField(max_length=128)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='swipeevent',
            name='music_swipe_user_id_1c9839_idx',
        ),
        migrations.RemoveField(
            model_name='swipeevent',
            name='user_id',
        ),
        migrations.AddField(
            model_name='swipeevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipe_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='album_art_url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('provider', 'provider_track_id')},
        ),
        migrations.AddIndex(
            model_name='swipeevent',
            index=models.Index(fields=['user'], name='music_swipe_user_id_1c9839_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['provider', 'provider_track_id'], name='music_track_provide_89266f_idx'),
        ),
        migrations.AddField(
            model_name='usertracklike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usertracklike',
            index=models.Index(fields=['user'], name='music_usert_user_id_b53968_idx'),
        ),
        migrations.AddIndex(
            model_name='usertracklike',
            index=models.Index(fields=['provider', 'provider_track_id'], name='music_usert_provide_fd269e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertracklike',
            unique_together={('user', 'provider', 'provider_track_id')},
        ),
    ]
